export const courses = [
  {
    id: 1,
    title: "Data Science",
    duration: "3 months",
    category: "Technology",
    rating: "4.5",
    instructor: "Dr. Alice Smith",
    description: "An introduction to data science concepts and techniques.",
    syllabus: "Python, Statistics, Machine Learning, Data Visualization",
    thumbnail:
      "https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/0786339c-e124-47fc-9e7a-67ca3a71db1e.png classroom with students working on data science projects, computers and charts visible",
  },
  {
    id: 2,
    title: "Web Development",
    duration: "4 months",
    category: "Technology",
    rating: "4.7",
    instructor: "Mr. John Doe",
    description:
      "Learn to build dynamic websites using HTML, CSS, and JavaScript.",
    syllabus: "HTML, CSS, JavaScript, React, Node.js",
    thumbnail:
      "https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/75f8e676-de96-4ad4-9f68-0d843d6dc689.png desk setup with monitor displaying code editor and website preview",
  },
  {
    id: 3,
    title: "Machine Learning",
    duration: "5 months",
    category: "Technology",
    rating: "4.8",
    instructor: "Dr. Emily Johnson",
    description: "Deep dive into machine learning algorithms and applications.",
    syllabus: "Supervised Learning, Unsupervised Learning, Neural Networks",
    thumbnail:
      "https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/daf0f2ad-c851-40c6-b58a-f4b30d6292d8.png AI brain visualization with data flow and neural connections",
  },
  {
    id: 4,
    title: "Digital Marketing",
    duration: "2 months",
    category: "Business",
    rating: "4.6",
    instructor: "Ms. Sarah Lee",
    description: "Explore the fundamentals of digital marketing strategies.",
    syllabus: "SEO, SEM, Social Media Marketing, Content Marketing",
    thumbnail:
      "https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/b7dc85b5-d944-46af-932b-ef5646f4474d.png strategy chart and digital devices showing analytics and social media icons",
  },
  {
    id: 5,
    title: "Graphic Design",
    duration: "3 months",
    category: "Creative Arts",
    rating: "4.4",
    instructor: "Mr. David Brown",
    description:
      "Learn the principles of graphic design and visual communication.",
    syllabus: "Adobe Photoshop, Illustrator, Design Theory",
    thumbnail:
      "https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/1f5c4523-1001-4c1f-a411-95d2170d143e.png workspace with color palettes, sketches and digital design tools",
  },
  {
    id: 6,
    title: "Cybersecurity",
    duration: "6 months",
    category: "Technology",
    rating: "4.9",
    instructor: "Dr. Michael Green",
    description:
      "Understand the fundamentals of cybersecurity and risk management.",
    syllabus: "Network Security, Ethical Hacking, Risk Assessment",
    thumbnail:
      "https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/608e769a-5032-4ebd-8451-e53a549ac660.png lock symbol over digital network background representing cybersecurity",
  },
  {
    id: 7,
    title: "Project Management",
    duration: "4 months",
    category: "Business",
    rating: "4.5",
    instructor: "Ms. Laura White",
    description: "Learn how to manage projects effectively and efficiently.",
    syllabus: "Agile, Scrum, Project Planning, Risk Management",
    thumbnail:
      "https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/cd570a89-a8c7-4d67-9707-9db1dc5b68a0.png collaborating in meeting room with charts and project plans",
  },
  {
    id: 8,
    title: "Artificial Intelligence",
    duration: "5 months",
    category: "Technology",
    rating: "4.8",
    instructor: "Dr. Robert Black",
    description: "Explore the concepts and applications of AI technologies.",
    syllabus: "Machine Learning, Natural Language Processing, Robotics",
    thumbnail:
      "https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/678fef8a-27e6-42af-ac0a-2fc76daae4dd.png robotic hand touching holographic AI icons",
  },
  {
    id: 9,
    title: "Mobile App Development",
    duration: "4 months",
    category: "Technology",
    rating: "4.6",
    instructor: "Mr. Chris Blue",
    description: "Learn to create mobile applications for iOS and Android.",
    syllabus: "Swift, Kotlin, React Native, UI/UX Design",
    thumbnail:
      "https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/374f73a6-d21d-4ea0-8d6a-239e0ebd08ee.png devices displaying app wireframes and development environment",
  },
  {
    id: 10,
    title: "Data Analysis",
    duration: "3 months",
    category: "Technology",
    rating: "4.7",
    instructor: "Dr. Jessica Gray",
    description: "Master data analysis techniques using Python and R.",
    syllabus: "Pandas, NumPy, Data Visualization, Statistical Analysis",
    thumbnail:
      "https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/29c9748c-7cef-42f6-a903-9c7eb5697907.png and charts on a computer screen showing data analysis",
  },
  {
    id: 11,
    title: "Cloud Computing",
    duration: "5 months",
    category: "Technology",
    rating: "4.8",
    instructor: "Mr. Kevin Red",
    description: "Understand cloud services and deployment models.",
    syllabus: "AWS, Azure, Google Cloud, Cloud Security",
    thumbnail:
      "https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/7201f318-17ba-4c3c-8e7b-0bcdcc968ec9.png icons connected with server racks representing cloud computing",
  },
  {
    id: 12,
    title: "Blockchain Technology",
    duration: "4 months",
    category: "Technology",
    rating: "4.7",
    instructor: "Dr. Nancy Purple",
    description:
      "Learn about blockchain and its applications in various industries.",
    syllabus: "Cryptography, Smart Contracts, Decentralized Applications",
    thumbnail:
      "https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/29225f16-8581-463c-81e6-bba53caf40b9.png nodes interconnected with digital ledger",
  },
  {
    id: 13,
    title: "Financial Analysis",
    duration: "3 months",
    category: "Business",
    rating: "4.5",
    instructor: "Mr. Tom Orange",
    description:
      "Explore financial analysis techniques for business decision-making.",
    syllabus: "Financial Statements, Ratio Analysis, Forecasting",
    thumbnail:
      "https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/7f17827b-e13e-4fbd-8e7b-b55ce95cc168.png charts and calculators on office desk",
  },
  {
    id: 14,
    title: "User Experience Design",
    duration: "3 months",
    category: "Creative Arts",
    rating: "4.6",
    instructor: "Ms. Rachel Pink",
    description: "Learn the principles of user-centered design.",
    syllabus: "User Research, Prototyping, Usability Testing",
    thumbnail:
      "https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/59fb5458-03ac-464a-a50e-a14954aea909.png working on wireframes and user journey maps",
  },
  {
    id: 15,
    title: "Entrepreneurship",
    duration: "2 months",
    category: "Business",
    rating: "4.4",
    instructor: "Mr. Steve Yellow",
    description:
      "Understand the fundamentals of starting and running a business.",
    syllabus: "Business Models, Funding, Marketing Strategies",
    thumbnail:
      "https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/47f04f7a-b838-499a-8c14-211cdbdd19b6.png pitching startup ideas in a business meeting",
  },
  {
    id: 16,
    title: "Photography",
    duration: "3 months",
    category: "Creative Arts",
    rating: "4.5",
    instructor: "Ms. Anna Cyan",
    description: "Learn the art and techniques of photography.",
    syllabus: "Camera Basics, Composition, Editing",
    thumbnail:
      "https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/6a14aed4-04dc-48cf-9dfc-512eb5a7ff82.png holding camera shooting outdoor portraits",
  },
  {
    id: 17,
    title: "Public Speaking",
    duration: "2 months",
    category: "Personal Development",
    rating: "4.6",
    instructor: "Mr. Paul Grey",
    description: "Develop effective public speaking and presentation skills.",
    syllabus: "Speech Writing, Body Language, Audience Engagement",
    thumbnail:
      "https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/1fab7502-eeba-4d39-9540-8b42214f5918.png speaking to an audience on stage with microphone",
  },
  {
    id: 18,
    title: "Social Media Management",
    duration: "2 months",
    category: "Business",
    rating: "4.5",
    instructor: "Ms. Lisa Brown",
    description: "Learn to manage and grow social media accounts effectively.",
    syllabus: "Content Creation, Analytics, Strategy Development",
    thumbnail:
      "https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/8e7d7701-e8cf-469f-a135-2c57feb355d8.png media icons and analytics displayed on a laptop screen",
  },
  {
    id: 19,
    title: "Data Visualization",
    duration: "3 months",
    category: "Technology",
    rating: "4.7",
    instructor: "Dr. Mark White",
    description: "Master the art of visualizing data for better insights.",
    syllabus: "Tableau, Power BI, D3.js",
    thumbnail:
      "https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/f28388cd-0ed7-4cb7-a0a5-bddcb797b2cb.png data charts and graphs on digital displays",
  },
  {
    id: 20,
    title: "Game Development",
    duration: "5 months",
    category: "Technology",
    rating: "4.8",
    instructor: "Mr. Jack Black",
    description: "Learn to create engaging video games from scratch.",
    syllabus: "Unity, C#, Game Design Principles",
    thumbnail:
      "https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/69d8b890-25fa-45ed-95f2-02eaf7617f5d.png game characters and development tools on dual monitors",
  },
];
