export const courses = [
  {
    id: 1,
    title: "Data Science",
    duration: "3 months",
    category: "Technology",
    rating: "4.5",
    instructor: "John Ndhlovu",
    description: "An introduction to data science concepts and techniques.",
    syllabus: "Python, Statistics, Machine Learning, Data Visualization",
    thumbnail: "/images/course1.webp",
  },
  {
    id: 2,
    title: "Web Development",
    duration: "4 months",
    category: "Technology",
    rating: "4.7",
    instructor: "Kevin Maseko",
    description:
      "Learn to build dynamic websites using HTML, CSS, and JavaScript.",
    syllabus: "HTML, CSS, JavaScript, React, Node.js",
    thumbnail: "/images/course2.webp",
  },
  {
    id: 3,
    title: "Machine Learning",
    duration: "5 months",
    category: "Technology",
    rating: "4.8",
    instructor: "Stephen Chirwa",
    description: "Deep dive into machine learning algorithms and applications.",
    syllabus: "Supervised Learning, Unsupervised Learning, Neural Networks",
    thumbnail: "/images/course3.jpeg",
  },
  {
    id: 4,
    title: "Digital Marketing",
    duration: "2 months",
    category: "Business",
    rating: "4.6",
    instructor: "Samuel Mwangi",
    description: "Explore the fundamentals of digital marketing strategies.",
    syllabus: "SEO, SEM, Social Media Marketing, Content Marketing",
    thumbnail: "/images/course4.jpg",
  },
  {
    id: 5,
    title: "Graphic Design",
    duration: "3 months",
    category: "Creative Arts",
    rating: "4.4",
    instructor: "Mark Katongo",
    description:
      "Learn the principles of graphic design and visual communication.",
    syllabus: "Adobe Photoshop, Illustrator, Design Theory",
    thumbnail: "/images/course1.webp",
  },
  {
    id: 6,
    title: "Cybersecurity",
    duration: "6 months",
    category: "Technology",
    rating: "4.9",
    instructor: "Lawrence Ncube",
    description:
      "Understand the fundamentals of cybersecurity and risk management.",
    syllabus: "Network Security, Ethical Hacking, Risk Assessment",
    thumbnail: "/images/course2.webp",
  },
  {
    id: 7,
    title: "Project Management",
    duration: "4 months",
    category: "Business",
    rating: "4.5",
    instructor: "Tevin Tshabalala",
    description: "Learn how to manage projects effectively and efficiently.",
    syllabus: "Agile, Scrum, Project Planning, Risk Management",
    thumbnail: "/images/course3.jpeg",
  },
  {
    id: 8,
    title: "Artificial Intelligence",
    duration: "5 months",
    category: "Technology",
    rating: "4.8",
    instructor: "John Zulu",
    description: "Explore the concepts and applications of AI technologies.",
    syllabus: "Machine Learning, Natural Language Processing, Robotics",
    thumbnail: "/images/course4.jpg",
  },
  {
    id: 9,
    title: "Mobile App Development",
    duration: "4 months",
    category: "Technology",
    rating: "4.6",
    instructor: "Kevin Kabwe",
    description: "Learn to create mobile applications for iOS and Android.",
    syllabus: "Swift, Kotlin, React Native, UI/UX Design",
    thumbnail: "/images/course1.webp",
  },
  {
    id: 10,
    title: "Data Analysis",
    duration: "3 months",
    category: "Technology",
    rating: "4.7",
    instructor: "Stephen Banda",
    description: "Master data analysis techniques using Python and R.",
    syllabus: "Pandas, NumPy, Data Visualization, Statistical Analysis",
    thumbnail: "/images/course2.webp",
  },
  {
    id: 11,
    title: "Cloud Computing",
    duration: "5 months",
    category: "Technology",
    rating: "4.8",
    instructor: "Samuel Sibiya",
    description: "Understand cloud services and deployment models.",
    syllabus: "AWS, Azure, Google Cloud, Cloud Security",
    thumbnail: "/images/course3.jpeg",
  },
  {
    id: 12,
    title: "Blockchain Technology",
    duration: "4 months",
    category: "Technology",
    rating: "4.7",
    instructor: "Mark Kato",
    description:
      "Learn about blockchain and its applications in various industries.",
    syllabus: "Cryptography, Smart Contracts, Decentralized Applications",
    thumbnail: "/images/course4.jpg",
  },
  {
    id: 13,
    title: "Financial Analysis",
    duration: "3 months",
    category: "Business",
    rating: "4.5",
    instructor: "Lawrence Mwale",
    description:
      "Explore financial analysis techniques for business decision-making.",
    syllabus: "Financial Statements, Ratio Analysis, Forecasting",
    thumbnail: "/images/course1.webp",
  },
  {
    id: 14,
    title: "User Experience Design",
    duration: "3 months",
    category: "Creative Arts",
    rating: "4.6",
    instructor: "Tevin Njoroge",
    description: "Learn the principles of user-centered design.",
    syllabus: "User Research, Prototyping, Usability Testing",
    thumbnail: "/images/course2.webp",
  },
  {
    id: 15,
    title: "Entrepreneurship",
    duration: "2 months",
    category: "Business",
    rating: "4.4",
    instructor: "John Lumumba",
    description:
      "Understand the fundamentals of starting and running a business.",
    syllabus: "Business Models, Funding, Marketing Strategies",
    thumbnail: "/images/course3.jpeg",
  },
  {
    id: 16,
    title: "Photography",
    duration: "3 months",
    category: "Creative Arts",
    rating: "4.5",
    instructor: "Kevin Otieno",
    description: "Learn the art and techniques of photography.",
    syllabus: "Camera Basics, Composition, Editing",
    thumbnail: "/images/course4.jpg",
  },
  {
    id: 17,
    title: "Public Speaking",
    duration: "2 months",
    category: "Personal Development",
    rating: "4.6",
    instructor: "Stephen Chibwe",
    description: "Develop effective public speaking and presentation skills.",
    syllabus: "Speech Writing, Body Language, Audience Engagement",
    thumbnail: "/images/course1.webp",
  },
  {
    id: 18,
    title: "Social Media Management",
    duration: "2 months",
    category: "Business",
    rating: "4.5",
    instructor: "Samuel Kamau",
    description: "Learn to manage and grow social media accounts effectively.",
    syllabus: "Content Creation, Analytics, Strategy Development",
    thumbnail: "/images/course2.webp",
  },
  {
    id: 19,
    title: "Data Visualization",
    duration: "3 months",
    category: "Technology",
    rating: "4.7",
    instructor: "Mark Musonda",
    description: "Master the art of visualizing data for better insights.",
    syllabus: "Tableau, Power BI, D3.js",
    thumbnail: "/images/course3.jpeg",
  },
  {
    id: 20,
    title: "Game Development",
    duration: "5 months",
    category: "Technology",
    rating: "4.8",
    instructor: "Lawrence Nkosi",
    description: "Learn to create engaging video games from scratch.",
    syllabus: "Unity, C#, Game Design Principles",
    thumbnail: "/images/course4.jpg",
  },
];
