export const courses = [
  {
    id: 1,
    title: "Data Science",
    duration: "",
    category: "",
    rating: "",
    instructor: "",
    description: "",
    syllabus: "",
  },
  {
    id: 2,
    title: "Data Science",
    duration: "",
    category: "",
    rating: "",
    instructor: "",
    description: "",
    syllabus: "",
  },
  {
    id: 3,
    title: "Data Science",
    duration: "",
    category: "",
    rating: "",
    instructor: "",
    description: "",
    syllabus: "",
  },
  {
    id: 4,
    title: "Data Science",
    duration: "",
    category: "",
    rating: "",
    instructor: "",
    description: "",
    syllabus: "",
  },
  {
    id: 5,
    title: "Data Science",
    duration: "",
    category: "",
    rating: "",
    instructor: "",
    description: "",
    syllabus: "",
  },
];
